@url = http://localhost:5002

### Tool list
POST {{url}}/
Content-Type: application/json
Accept: application/json, text/event-stream

{
  "jsonrpc": "2.0",
  "id": "1",
  "method": "tools/list"
}

### Call: get_exchange_rate
POST {{url}}/
Content-Type: application/json
Accept: application/json, text/event-stream

{
  "jsonrpc": "2.0",
  "id": "3",
  "method": "tools/call",
  "params": {
    "name": "get_currency_exchange_rate",
    "arguments": {
      "baseCurrency": "USD",
      "targetCurrency": "PLN"
    }
  }
}